[package]
name = "tw_aura"
version = "0.4.0"
edition = "2024"

[dependencies]
twitch_api = {version = "0.7", features = ["helix", "client", "reqwest", "twitch_oauth2"]}
reqwest = {version = "0.12", default-features = false, features = ["json", "http2", "rustls-tls"]}
tokio = { version = "1", features = ["full"] }
image = "0.25"
egui = { version = "0.36.2" }
egui_extras = { version = "0.36", default-features = false, features = [
    "image",
    "http",
    "gif",
    "webp",
] }
eframe = { version = "0.36.2", default-features = false, features = [
    "glow",
    "default_fonts",
    "wayland",
    "accesskit",
], optional = true}
egui_glow = "0.36.2"
aurora_egui = { git = "https://github.com/auroraos-rs/aurora-gui", optional = true }
# aurora_services = { version = "0.1.1", optional = true }
aurora_services = { git = "https://github.com/auroraos-rs/aurora_services", optional = true }
egui-rotate = "3.1.2"
futures = "0.3"
ring-channel = "0.12"
thiserror = "2.0"
m3u8-rs = "6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ffmpeg-next = { version = "8.0.0", default-features = false, features = [ "codec", "format", "software-resampling", "build", "build-lib-openssl", "build-lib-x264", "build-license-version3", "build-license-gpl", "static" ] }
glow = "0.17.0"

anyhow = "1.0"
libpulse-binding = "2.30.1"
libpulse-simple-binding = "2.29.0"
log = "0.4"
env_logger = "0.11"

[features]
default = ["desktop"]
aurora = ["aurora_egui", "aurora_services"]
desktop = ["eframe"]

[profile.release]
strip = true

[package.metadata.generate-rpm]
name = "com.lmaxyz.TwAura"
license = "Apache-2.0"
summary = "Twitch Client"
release = "1"
url = "https://github.com/lmaxyz/tw_aura"
assets = [
    { source = "target/release/tw_aura", dest = "/usr/bin/com.lmaxyz.TwAura", mode = "755" },
    { source = "rpm/com.lmaxyz.TwAura.desktop", dest = "/usr/share/applications/com.lmaxyz.TwAura.desktop", mode = "644" },
    { source = "rpm/icons/86x86/com.lmaxyz.TwAura.png", dest = "/usr/share/icons/hicolor/86x86/apps/com.lmaxyz.TwAura.png", mode = "644" },
    { source = "rpm/icons/108x108/com.lmaxyz.TwAura.png", dest = "/usr/share/icons/hicolor/108x108/apps/com.lmaxyz.TwAura.png", mode = "644" },
    { source = "rpm/icons/128x128/com.lmaxyz.TwAura.png", dest = "/usr/share/icons/hicolor/128x128/apps/com.lmaxyz.TwAura.png", mode = "644" },
    { source = "rpm/icons/172x172/com.lmaxyz.TwAura.png", dest = "/usr/share/icons/hicolor/172x172/apps/com.lmaxyz.TwAura.png", mode = "644" },
]
auto-req = "no"

[patch.crates-io]
# winit = { git = "https://github.com/lmaxyz/winit", branch = "rm_maliit" }
glutin = { git = "https://github.com/lmaxyz/glutin", branch = "aurora_device_fix" }
eframe = { git = "https://github.com/lmaxyz/egui/", branch = "aurora_winit" }
egui-winit = { git = "https://github.com/lmaxyz/egui/", branch = "aurora_winit" }
egui_glow = { git = "https://github.com/lmaxyz/egui/", branch = "aurora_winit" }
epaint = { git = "https://github.com/lmaxyz/egui/", branch = "aurora_winit" }
emath = { git = "https://github.com/lmaxyz/egui/", branch = "aurora_winit" }
egui = { git = "https://github.com/lmaxyz/egui/", branch = "aurora_winit" }
