[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--disable-new-dtags", "-C", "link-arg=-Wl,-rpath,$ORIGIN/../share/com.lmaxyz.TwAura/lib", "-C", "link-arg=-L/usr/share/com.lmaxyz.TwAura/lib"]
